### ISSUE TITLE
WIP: action to update a readme, markdown, github profile etc

### ISSUE THREAD

**Issue by thiago-scherrer** [climateclock/climate-clock-widget#7]
Hello everyone!

I create a GitHub Action https://github.com/thiago-scherrer/climateclock-gh-action
This action allows update automatically and periodically Markdown/PNG file with the climate clock from [climateclock.world](https://www.climateclock.world/).

I put this action to update my github profile: 
![Screenshot_20230517-001005_kindlephoto-127062573](https://github.com/climateclock/climate-clock-widget/assets/46422437/905fcbd1-6c08-4362-96a3-0b56f9193155)

If you have any questions or feedback, please don't hesitate to reach out. Contributions and suggestions are always welcome!

Thank you for your for this project and let's make a difference together!

Best regards, (sorry my issue spam)

**Comment by adrian-the-git** [comment]
Nice, great use of the github action. Is the 50 minute update interval arbitrary, or a compromise based on cost, something else?

**Comment by thiago-scherrer** [comment]
>Nice, great use of the github action. Is the 50 minute update interval arbitrary, or a compromise based on >cost, something else?

Thanks! The 50-minute update is arbitrary and fully customizable. I chose this value solely to minimize power consumption, but I came up with it without conducting any studies on energy consumption or similar factors.

**Comment by thiago-scherrer** [comment]
Thank you for the project! If I can be of any assistance, count me in!
